spring:
  application:
    name: learn-graphql-java
    
server:
  http2:
    enabled: true
    
graphql:
  servlet:
    maxQueryDepth: 6
    exeption-handlers-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    enabled: true
  voyager:
    enabled: true
