name: pr

on:
  pull_request:
    branches:
      - "*"
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  run_something:    
    if: github.event.pull_request.draft == false
    name: Run something
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Show diff
        run: |
          git show --pretty=format:'' --name-only ${{ github.sha }}
          
